# Horizontal Pod Autoscaler for price-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: price-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tick12-price-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80